require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TennisController do

  # This should return the minimal set of attributes required to create a valid
  # Tenni. As you add validations to Tenni, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TennisController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tennis as @tennis" do
      tenni = Tenni.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tennis).should eq([tenni])
    end
  end

  describe "GET show" do
    it "assigns the requested tenni as @tenni" do
      tenni = Tenni.create! valid_attributes
      get :show, {:id => tenni.to_param}, valid_session
      assigns(:tenni).should eq(tenni)
    end
  end

  describe "GET new" do
    it "assigns a new tenni as @tenni" do
      get :new, {}, valid_session
      assigns(:tenni).should be_a_new(Tenni)
    end
  end

  describe "GET edit" do
    it "assigns the requested tenni as @tenni" do
      tenni = Tenni.create! valid_attributes
      get :edit, {:id => tenni.to_param}, valid_session
      assigns(:tenni).should eq(tenni)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tenni" do
        expect {
          post :create, {:tenni => valid_attributes}, valid_session
        }.to change(Tenni, :count).by(1)
      end

      it "assigns a newly created tenni as @tenni" do
        post :create, {:tenni => valid_attributes}, valid_session
        assigns(:tenni).should be_a(Tenni)
        assigns(:tenni).should be_persisted
      end

      it "redirects to the created tenni" do
        post :create, {:tenni => valid_attributes}, valid_session
        response.should redirect_to(Tenni.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tenni as @tenni" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tenni.any_instance.stub(:save).and_return(false)
        post :create, {:tenni => {}}, valid_session
        assigns(:tenni).should be_a_new(Tenni)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tenni.any_instance.stub(:save).and_return(false)
        post :create, {:tenni => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tenni" do
        tenni = Tenni.create! valid_attributes
        # Assuming there are no other tennis in the database, this
        # specifies that the Tenni created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tenni.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tenni.to_param, :tenni => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tenni as @tenni" do
        tenni = Tenni.create! valid_attributes
        put :update, {:id => tenni.to_param, :tenni => valid_attributes}, valid_session
        assigns(:tenni).should eq(tenni)
      end

      it "redirects to the tenni" do
        tenni = Tenni.create! valid_attributes
        put :update, {:id => tenni.to_param, :tenni => valid_attributes}, valid_session
        response.should redirect_to(tenni)
      end
    end

    describe "with invalid params" do
      it "assigns the tenni as @tenni" do
        tenni = Tenni.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tenni.any_instance.stub(:save).and_return(false)
        put :update, {:id => tenni.to_param, :tenni => {}}, valid_session
        assigns(:tenni).should eq(tenni)
      end

      it "re-renders the 'edit' template" do
        tenni = Tenni.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tenni.any_instance.stub(:save).and_return(false)
        put :update, {:id => tenni.to_param, :tenni => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tenni" do
      tenni = Tenni.create! valid_attributes
      expect {
        delete :destroy, {:id => tenni.to_param}, valid_session
      }.to change(Tenni, :count).by(-1)
    end

    it "redirects to the tennis list" do
      tenni = Tenni.create! valid_attributes
      delete :destroy, {:id => tenni.to_param}, valid_session
      response.should redirect_to(tennis_url)
    end
  end

end
